"""Generate a Swift client for OpenAPI documents outside the pinned Hermes contract.

Services that run beside Hermes, such as dashboard plugins, describe their routes in their own
OpenAPI 3 documents. This generates one Swift module from them with the same naming, models and
decoding rules as HermesAPI's own REST client: every operation of the documents becomes a method of
one catalog type, and the methods run over any HermesAPI ``RESTCalling``. An app therefore calls
them through the ``HermesREST`` it already has, with its credential, address, retries and deadlines.

Unlike the pinned release, these documents are the reviewed contract themselves, so every operation
is generated. Several documents are merged; a path or a differing schema defined twice fails.

    uv run python -m tools.gen_openapi_client --spec mail.yaml --spec vault.yaml \\
        --catalog PluginCatalog --swift-out ../app/Sources/PluginAPI
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

from tools.gen_gateway_models import declarations
from tools.gen_rest_api import (
    METHODS,
    RUNTIME_NAMES,
    Operation,
    _swift,
    _swift_decode,
    _swift_method,
    _swift_result_enum,
    build,
)
from tools.naming import pascal

TOOL = "tools/gen_openapi_client.py"
PER_FILE = 35
# `Decoder.decodesTolerantly` and `DynamicCodingKey` are internal to HermesAPI, so the generated module
# declares its own. The key must match `CodingUserInfoKey.restDecoding` in the runtime (HermesREST.swift),
# which `RESTResponse.json(_:status:)` sets; a test checks that it does.
DECODING_KEY = "hermes.api.rest.decoding"
SUPPORT = f"""// Generated by {TOOL}. Do not edit.
import Foundation
import HermesAPI

extension Decoder {{
    /// Whether generated models skip what their contract does not declare (`RESTDecoding.tolerant`).
    var decodesTolerantly: Bool {{
        guard let key = CodingUserInfoKey(rawValue: "{DECODING_KEY}") else {{ return false }}
        return userInfo[key] as? RESTDecoding == .tolerant
    }}
}}

struct DynamicCodingKey: CodingKey {{
    let stringValue: String
    let intValue: Int? = nil

    init(_ value: String) {{ stringValue = value }}
    init?(stringValue: String) {{ self.stringValue = stringValue }}
    init?(intValue: Int) {{ return nil }}
}}
"""


def _inline(document: dict, value: object, section: str) -> object:
    """``value`` with a reference to ``#/components/<section>/…`` replaced by its target."""
    if isinstance(value, dict) and set(value) == {"$ref"}:
        prefix = f"#/components/{section}/"
        if not value["$ref"].startswith(prefix):
            raise ValueError(f"Unsupported {section} reference {value['$ref']}")
        name = value["$ref"].removeprefix(prefix)
        target = document.get("components", {}).get(section, {}).get(name)
        if target is None:
            raise ValueError(f"Unresolved reference {value['$ref']}")
        return target
    return value


def _operations(document: dict, item: dict) -> dict:
    """A path item's operations, with path-level and referenced parameters and responses inlined."""
    shared = [_inline(document, parameter, "parameters") for parameter in item.get("parameters", [])]
    operations = {}
    for method in METHODS:
        if method not in item:
            continue
        operation = dict(item[method])
        own = [_inline(document, parameter, "parameters") for parameter in operation.get("parameters", [])]
        names = {(parameter["name"], parameter["in"]) for parameter in own}
        operation["parameters"] = own + [p for p in shared if (p["name"], p["in"]) not in names]
        operation["responses"] = {status: _inline(document, response, "responses")
                                  for status, response in operation.get("responses", {}).items()}
        if "requestBody" in operation:
            operation["requestBody"] = _inline(document, operation["requestBody"], "requestBodies")
        operations[method] = operation
    unsupported = set(item) - set(METHODS) - {"parameters", "summary", "description"}
    if unsupported:
        raise ValueError(f"Unsupported path item keys {sorted(unsupported)}")
    return operations


def load(paths: list[Path]) -> dict:
    """The documents merged into one: their operations and component schemas."""
    merged: dict = {"paths": {}, "components": {"schemas": {}}}
    for path in paths:
        text = path.read_text(encoding="utf-8")
        document = json.loads(text) if path.suffix == ".json" else yaml.safe_load(text)
        if not str(document.get("openapi", "")).startswith("3."):
            raise ValueError(f"Not an OpenAPI 3 document: {path}")
        for route, item in document.get("paths", {}).items():
            if route in merged["paths"]:
                raise ValueError(f"Path {route} is defined twice (again in {path})")
            merged["paths"][route] = _operations(document, item)
        for name, schema in document.get("components", {}).get("schemas", {}).items():
            existing = merged["components"]["schemas"].setdefault(name, schema)
            if existing != schema:
                raise ValueError(f"Schema {name} is defined differently in {path}")
    return merged


def _catalog(ops: list[Operation], catalog: str, sources: list[str], taken: set[str]) -> str:
    groups: dict[str, list[Operation]] = {}
    for op in ops:
        groups.setdefault(op.namespace, []).append(op)
    types = {namespace: f"{pascal(namespace)}Methods" for namespace in groups}
    clashes = sorted(name for name in [catalog, *types.values()] if name in taken)
    if clashes:
        raise ValueError(f"Catalog type names collide with generated models: {clashes}")
    lines = [f"// Generated by {TOOL} from {', '.join(sources)}. Do not edit.", "import Foundation",
             "import HermesAPI", "",
             "/// Every operation of the documents, by namespace: the plugin for `/api/plugins/<plugin>/…`,",
             "/// the first segment after `/api/` otherwise.",
             f"public struct {catalog}: Sendable {{", "    private let caller: any RESTCalling",
             "    public init(caller: any RESTCalling) { self.caller = caller }"]
    for namespace in sorted(groups):
        lines.append(f"    public var {_swift(namespace)}: {types[namespace]} {{ {types[namespace]}(caller: caller) }}")
    for namespace, entries in sorted(groups.items()):
        lines.extend(["", f"    public struct {types[namespace]}: Sendable {{",
                      "        private let caller: any RESTCalling",
                      "        init(caller: any RESTCalling) { self.caller = caller }"])
        for op in sorted(entries, key=lambda item: item.name):
            lines.append("")
            lines.extend("    " + line for line in _swift_method(op))
        lines.append("    }")
    lines.append("}")
    lines.extend(["", *_decoders(ops, catalog)])
    for op in ops:
        if op.result_name:
            lines.extend(["", _swift_result_enum(op)])
    return "\n".join(lines) + "\n"


def _decoders(ops: list[Operation], catalog: str) -> list[str]:
    """Every operation by `METHOD /path`, and a decoder for recorded responses, for contract tests."""
    lines = [f"extension {catalog} {{", "    /// Every operation, as `METHOD /path`.",
             "    public static let operations: [String] = [",
             *[f'        "{op.method} {op.path}",' for op in ops], "    ]", "",
             "    /// Decodes a response to `operation` (`METHOD /path`) with its generated result type, the way",
             "    /// the operation's method does; for checking recorded responses against the contract.",
             "    public static func decode(_ operation: String, _ response: RESTResponse) throws -> any Sendable {",
             "        switch operation {"]
    for op in ops:
        lines.append(f'        case "{op.method} {op.path}":')
        outcomes = op.outcomes
        if len(outcomes) == 1:
            outcome = outcomes[0]
            if outcome.kind == "empty":
                lines.append(f"            try response.empty(status: {outcome.status}); return ()")
            else:
                lines.append(f"            return {_swift_decode(outcome)}")
            continue
        lines.append("            switch response.status {")
        for outcome in outcomes:
            if outcome.kind == "empty":
                lines.append(f"            case {outcome.status}: try response.empty(status: {outcome.status}); return ()")
            else:
                lines.append(f"            case {outcome.status}: return {_swift_decode(outcome)}")
        lines.extend(["            default: throw response.undocumented()", "            }"])
    lines.extend(['        default: throw HermesRESTError.decoding("Unknown operation \\(operation)")', "        }",
                  "    }", "}"])
    return lines


def outputs(specs: list[Path], catalog: str, out: Path, origin: str) -> tuple[dict[Path, str], list[Operation]]:
    document = load(specs)
    # Types the generated code names unqualified must not be shadowed by a schema; they get a prefix.
    graph, ops = build(document, set(RUNTIME_NAMES) | {"DynamicCodingKey", catalog}, include=lambda _: True)
    models = declarations(graph, origin)
    sources = [spec.name for spec in specs]
    header = f"// Generated by {TOOL}. Do not edit.\nimport Foundation\nimport HermesAPI\n\n"
    files: dict[Path, str] = {}
    for index in range(0, len(models), PER_FILE):
        batch = models[index:index + PER_FILE]
        files[out / f"Models{index // PER_FILE:02}.swift"] = header + "\n\n".join(item[1].strip() for item in batch) + "\n"
    taken = {name for name, _, _ in models} | {op.result_name for op in ops if op.result_name}
    files[out / f"{catalog}.swift"] = _catalog(ops, catalog, sources, taken)
    files[out / "Support.swift"] = SUPPORT
    return files, ops


def generate(specs: list[Path], catalog: str, out: Path, origin: str, *, check: bool = False) -> int:
    files, ops = outputs(specs, catalog, out, origin)
    stale = set(out.glob("*.swift")) - set(files)
    changed = [path for path, body in files.items()
               if not path.exists() or path.read_text(encoding="utf-8") != body]
    if check:
        if changed or stale:
            raise ValueError(f"Generated client stale: {sorted(str(p) for p in [*changed, *stale])}")
        return len(ops)
    for path in stale:
        path.unlink()
    for path, body in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8")
    return len(ops)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--spec", action="append", required=True, type=Path,
                        help="An OpenAPI 3 document (JSON or YAML); repeat to merge several.")
    parser.add_argument("--catalog", required=True, help="The Swift type that holds every namespace.")
    parser.add_argument("--swift-out", required=True, type=Path,
                        help="The directory the module's generated sources live in; other Swift files there are removed.")
    parser.add_argument("--origin", default="OpenAPI contract", help="Where the models come from, for their doc comments.")
    parser.add_argument("--check", action="store_true", help="Fail if the committed sources are stale.")
    args = parser.parse_args()
    count = generate(args.spec, args.catalog, args.swift_out, args.origin, check=args.check)
    print(f"Generated {count} operations into {args.catalog}")


if __name__ == "__main__":
    main()
